// vue-posts/src/components/AppNav.vue
<script setup>
import { computed } from 'vue';
import { RouterLink, useRoute } from 'vue-router';
import ChoogaBridge from '../bridge.js';
import { House, Plane, Search, Ticket, X } from '../icons.js';

const route = useRoute();

const isHome = computed(() => route.path === '/');
const isSearch = computed(() =>
  ['/search', '/results'].includes(route.path) || route.path.startsWith('/flight'),
);
const isBookings = computed(() =>
  route.path === '/bookings' || route.path.startsWith('/confirmation'),
);
</script>

<template>
  <nav class="app-nav" aria-label="Main">
    <RouterLink to="/" class="nav-item" :class="{ on: isHome }">
      <House :size="22" :stroke-width="2.1" />
      <span>Home</span>
    </RouterLink>
    <RouterLink to="/search" class="nav-item" :class="{ on: isSearch }">
      <Search :size="22" :stroke-width="2.1" />
      <span>Search</span>
    </RouterLink>
    <RouterLink to="/bookings" class="nav-item" :class="{ on: isBookings }">
      <Ticket :size="22" :stroke-width="2.1" />
      <span>Bookings</span>
    </RouterLink>
    <button type="button" class="nav-item" @click="ChoogaBridge.close()">
      <X :size="22" :stroke-width="2.1" />
      <span>Close</span>
    </button>
  </nav>
</template>

// react-store/src/components/AppNav.jsx
import {NavLink} from 'react-router-dom';
import ChoogaBridge from '../bridge.js';
import {House, ShoppingCart, Store, X} from '../icons.jsx';

export default function AppNav({cartCount = 0}) {
  return (
    <nav className="app-nav" aria-label="Main">
      <NavLink to="/" end className={({isActive}) => (isActive ? 'nav-item on' : 'nav-item')}>
        <House size={22} strokeWidth={2.1} />
        <span>Home</span>
      </NavLink>
      <NavLink
        to="/products"
        className={({isActive}) => (isActive ? 'nav-item on' : 'nav-item')}>
        <Store size={22} strokeWidth={2.1} />
        <span>Market</span>
      </NavLink>
      <NavLink
        to="/checkout"
        className={({isActive}) => (isActive ? 'nav-item on' : 'nav-item')}>
        <span className="nav-icon-wrap">
          <ShoppingCart size={22} strokeWidth={2.1} />
          {cartCount > 0 ? <span className="nav-badge">{cartCount}</span> : null}
        </span>
        <span>Cart</span>
      </NavLink>
      <button
        type="button"
        className="nav-item"
        onClick={() => ChoogaBridge.close()}>
        <X size={22} strokeWidth={2.1} />
        <span>Close</span>
      </button>
    </nav>
  );
}
