// react-store/src/pages/Welcome.jsx
import {useEffect, useState} from 'react';
import {Link, useNavigate} from 'react-router-dom';
import ChoogaBridge, {displayNameFromUser, startBridge} from '../bridge.js';

export default function Welcome() {
  const navigate = useNavigate();
  const [state, setState] = useState(() => ChoogaBridge.getState());

  useEffect(() => {
    startBridge();
    return ChoogaBridge.subscribe(setState);
  }, []);

  const name = displayNameFromUser(state.user);

  return (
    <div className="stack welcome-panel">
      <div className="panel stack">
        <p className="eyebrow">Chooga Store</p>
        <h1>Welcome, {name}</h1>
        <p className="muted">
          {state.hostConnected
            ? 'You are signed in through Awash. Choose how you want to continue.'
            : 'Running in demo mode. Choose how you want to continue.'}
        </p>
        <div className="choice-grid">
          <button type="button" onClick={() => navigate('/products')}>
            Browse products
          </button>
          <button
            type="button"
            className="secondary"
            onClick={() => navigate('/checkout')}>
            View cart / checkout
          </button>
        </div>
        {state.hostConnected ? (
          <button
            type="button"
            className="secondary"
            onClick={() => ChoogaBridge.close()}>
            Close mini-app
          </button>
        ) : null}
      </div>
      <p className="muted">
        Or jump ahead: <Link to="/products">products</Link>
      </p>
    </div>
  );
}

// vue-posts/src/views/Welcome.vue
<script setup>
import { computed, onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import ChoogaBridge, { displayNameFromUser, startBridge } from '../bridge.js';

const router = useRouter();
const bridge = ref(ChoogaBridge.getState());

onMounted(() => {
  startBridge();
  ChoogaBridge.subscribe(state => {
    bridge.value = state;
  });
});

const name = computed(() => displayNameFromUser(bridge.value.user));
</script>

<template>
  <div class="stack welcome-panel">
    <div class="panel stack">
      <p class="eyebrow">Chooga Posts</p>
      <h1>Welcome, {{ name }}</h1>
      <p class="muted">
        {{
          bridge.hostConnected
            ? 'You are signed in through Awash. Choose how you want to continue.'
            : 'Running in demo mode. Choose how you want to continue.'
        }}
      </p>
      <div class="choice-grid">
        <button type="button" @click="router.push('/posts')">Browse posts</button>
        <button type="button" class="secondary" @click="router.push('/compose')">
          Compose a post
        </button>
      </div>
      <button
        v-if="bridge.hostConnected"
        type="button"
        class="secondary"
        @click="ChoogaBridge.close()"
      >
        Close mini-app
      </button>
    </div>
  </div>
</template>
